// StarScreener — Curated seed list of ~300 real GitHub repos.
//
// This list drives the production ingestion path when a GITHUB_TOKEN is
// available. Unlike `mock-data.ts` (which carries fully-synthesized metrics
// for offline dev), this file is only the `owner/repo` identifiers — the
// real GitHub adapter fetches metrics on demand and the pipeline fills in
// derived fields (deltas, momentum, rank, etc.).
//
// Keep this organized by category so operators can audit coverage at a
// glance. ~30 entries per category across all 10 supported categories.

// Category keys MUST match the categoryId values used in `constants.ts`
// and `mock-data.ts`. The pipeline types also expose a broader
// PipelineCategoryId union, but the runtime/UI is driven by these string ids.
export type SeedCategoryId =
  | "ai-ml"
  | "web-frameworks"
  | "devtools"
  | "infrastructure"
  | "databases"
  | "security"
  | "mobile"
  | "data-analytics"
  | "crypto-web3"
  | "rust-ecosystem";

export const SEED_REPOS: Record<SeedCategoryId, string[]> = {
  "ai-ml": [
    "ollama/ollama",
    "langchain-ai/langchain",
    "huggingface/transformers",
    "ggerganov/llama.cpp",
    "open-webui/open-webui",
    "AUTOMATIC1111/stable-diffusion-webui",
    "run-llama/llama_index",
    "mlc-ai/mlc-llm",
    "vllm-project/vllm",
    "pytorch/pytorch",
    "tensorflow/tensorflow",
    "openai/whisper",
    "microsoft/DeepSpeed",
    "facebookresearch/llama",
    "tatsu-lab/stanford_alpaca",
    "karpathy/nanoGPT",
    "karpathy/llm.c",
    "comfyanonymous/ComfyUI",
    "InvokeAI/InvokeAI",
    "unslothai/unsloth",
    "axolotl-ai-cloud/axolotl",
    "meta-llama/llama3",
    "mlfoundations/open_clip",
    "triton-lang/triton",
    "deepseek-ai/DeepSeek-V3",
    "lm-sys/FastChat",
    "guidance-ai/guidance",
    "outlines-dev/outlines",
    "ggerganov/whisper.cpp",
    "stanfordnlp/dspy",
    "microsoft/autogen",
    "crewAIInc/crewAI",
  ],

  "web-frameworks": [
    "vercel/next.js",
    "sveltejs/svelte",
    "vuejs/core",
    "remix-run/remix",
    "withastro/astro",
    "honojs/hono",
    "solidjs/solid",
    "angular/angular",
    "facebook/react",
    "nuxt/nuxt",
    "emberjs/ember.js",
    "preactjs/preact",
    "qwikdev/qwik",
    "redwoodjs/redwood",
    "fastify/fastify",
    "expressjs/express",
    "nestjs/nest",
    "koajs/koa",
    "strapi/strapi",
    "payloadcms/payload",
    "TanStack/router",
    "TanStack/query",
    "trpc/trpc",
    "wasp-lang/wasp",
    "marko-js/marko",
    "lit/lit",
    "alpinejs/alpine",
    "hotwired/turbo",
    "hotwired/stimulus",
    "phoenixframework/phoenix",
    "laravel/laravel",
    "rails/rails",
  ],

  "devtools": [
    "astral-sh/uv",
    "zed-industries/zed",
    "oven-sh/bun",
    "biomejs/biome",
    "oxc-project/oxc",
    "astral-sh/ruff",
    "denoland/deno",
    "typst/typst",
    "microsoft/vscode",
    "neovim/neovim",
    "helix-editor/helix",
    "prettier/prettier",
    "eslint/eslint",
    "webpack/webpack",
    "vitejs/vite",
    "rollup/rollup",
    "parcel-bundler/parcel",
    "evanw/esbuild",
    "swc-project/swc",
    "rome/tools",
    "nodejs/node",
    "microsoft/TypeScript",
    "tc39/proposals",
    "jestjs/jest",
    "vitest-dev/vitest",
    "playwright/playwright",
    "cypress-io/cypress",
    "storybookjs/storybook",
    "turbo/turbo",
    "nrwl/nx",
    "pnpm/pnpm",
    "yarnpkg/berry",
  ],

  "infrastructure": [
    "kubernetes/kubernetes",
    "docker/compose",
    "hashicorp/terraform",
    "grafana/grafana",
    "traefik/traefik",
    "pulumi/pulumi",
    "cloudflare/workers-sdk",
    "containers/podman",
    "moby/moby",
    "helm/helm",
    "argoproj/argo-cd",
    "argoproj/argo-workflows",
    "istio/istio",
    "linkerd/linkerd2",
    "cilium/cilium",
    "envoyproxy/envoy",
    "prometheus/prometheus",
    "open-telemetry/opentelemetry-collector",
    "jaegertracing/jaeger",
    "fluent/fluent-bit",
    "kedacore/keda",
    "crossplane/crossplane",
    "flux-cd/flux2",
    "kubevirt/kubevirt",
    "k3s-io/k3s",
    "coredns/coredns",
    "caddyserver/caddy",
    "nginx/nginx",
    "ansible/ansible",
    "saltstack/salt",
    "minio/minio",
  ],

  "databases": [
    "duckdb/duckdb",
    "pola-rs/polars",
    "tursodatabase/libsql",
    "dragonflydb/dragonfly",
    "valkey-io/valkey",
    "cockroachdb/cockroach",
    "timescale/timescaledb",
    "surrealdb/surrealdb",
    "postgres/postgres",
    "mysql/mysql-server",
    "mongodb/mongo",
    "redis/redis",
    "elastic/elasticsearch",
    "prisma/prisma",
    "drizzle-team/drizzle-orm",
    "supabase/supabase",
    "pocketbase/pocketbase",
    "questdb/questdb",
    "tikv/tikv",
    "pingcap/tidb",
    "yugabyte/yugabyte-db",
    "scylladb/scylladb",
    "chroma-core/chroma",
    "qdrant/qdrant",
    "weaviate/weaviate",
    "milvus-io/milvus",
    "pgvector/pgvector",
    "neo4j/neo4j",
    "influxdata/influxdb",
    "apache/cassandra",
    "citusdata/citus",
    "clickhouse/clickhouse",
  ],

  "security": [
    "projectdiscovery/nuclei",
    "trufflesecurity/trufflehog",
    "aquasecurity/trivy",
    "gitleaks/gitleaks",
    "crowdsecurity/crowdsec",
    "zaproxy/zaproxy",
    "semgrep/semgrep",
    "snyk/cli",
    "anchore/grype",
    "anchore/syft",
    "wazuh/wazuh",
    "Neo23x0/signature-base",
    "SigmaHQ/sigma",
    "OWASP/CheatSheetSeries",
    "SpiderLabs/ModSecurity",
    "StackExchange/blackbox",
    "hashicorp/vault",
    "bitwarden/server",
    "keycloak/keycloak",
    "openziti/ziti",
    "dropbox/zxcvbn",
    "FiloSottile/mkcert",
    "certbot/certbot",
    "lxc/lxc",
    "falcosecurity/falco",
    "cilium/tetragon",
    "quay/clair",
    "kubernetes-sigs/kube-bench",
    "future-architect/vuls",
    "OWASP/Amass",
    "subfinder/subfinder",
  ],

  "mobile": [
    "expo/expo",
    "tauri-apps/tauri",
    "facebook/react-native",
    "flutter/flutter",
    "ionic-team/ionic-framework",
    "ionic-team/capacitor",
    "NativeScript/NativeScript",
    "electron/electron",
    "apple/swift",
    "JetBrains/kotlin",
    "Kotlin/kotlinx.coroutines",
    "android/architecture-samples",
    "microsoft/maui",
    "dotnet/maui",
    "xamarin/xamarin-forms-samples",
    "vercel/satori",
    "gluestack/gluestack-ui",
    "callstack/react-native-paper",
    "software-mansion/react-native-reanimated",
    "software-mansion/react-native-gesture-handler",
    "invertase/react-native-firebase",
    "wix/Detox",
    "react-native-community/cli",
    "infinitered/ignite",
    "nativewind/nativewind",
    "Leaflet/Leaflet",
    "openlayers/openlayers",
    "mapbox/mapbox-gl-native",
    "realm/realm-swift",
    "realm/realm-kotlin",
    "mongodb/mongo-swift-driver",
  ],

  "data-analytics": [
    "apache/superset",
    "metabase/metabase",
    "evidence-dev/evidence",
    "apache/spark",
    "streamlit/streamlit",
    "grafana/loki",
    "meltano/meltano",
    "dbt-labs/dbt-core",
    "apache/airflow",
    "PrefectHQ/prefect",
    "dagster-io/dagster",
    "kestra-io/kestra",
    "apache/flink",
    "apache/kafka",
    "apache/beam",
    "apache/arrow",
    "apache/parquet-format",
    "apache/pinot",
    "apache/druid",
    "trinodb/trino",
    "pandas-dev/pandas",
    "numpy/numpy",
    "jupyter/notebook",
    "jupyterlab/jupyterlab",
    "plotly/plotly.py",
    "plotly/dash",
    "gradio-app/gradio",
    "quarto-dev/quarto-cli",
    "rstudio/shiny",
    "fivetran/dbt_utils",
    "getredash/redash",
    "mindsdb/mindsdb",
  ],

  "crypto-web3": [
    "paradigmxyz/reth",
    "foundry-rs/foundry",
    "solana-labs/solana",
    "ethereum/go-ethereum",
    "alloy-rs/alloy",
    "a16z/jolt",
    "starkware-libs/cairo",
    "MystenLabs/sui",
    "bitcoin/bitcoin",
    "ethereum/solidity",
    "vyperlang/vyper",
    "NomicFoundation/hardhat",
    "OpenZeppelin/openzeppelin-contracts",
    "wagmi-dev/wagmi",
    "ethers-io/ethers.js",
    "web3/web3.js",
    "anchor-lang/anchor",
    "cosmos/cosmos-sdk",
    "tendermint/tendermint",
    "near/nearcore",
    "polkadot-fellows/runtimes",
    "paritytech/polkadot-sdk",
    "ChainSafe/lodestar",
    "prysmaticlabs/prysm",
    "sigp/lighthouse",
    "status-im/nimbus-eth2",
    "Consensys/teku",
    "hyperledger/besu",
    "input-output-hk/cardano-node",
    "algorand/go-algorand",
    "ava-labs/avalanchego",
    "aptos-labs/aptos-core",
  ],

  "rust-ecosystem": [
    "tokio-rs/tokio",
    "leptos-rs/leptos",
    "bevyengine/bevy",
    "meilisearch/meilisearch",
    "starship/starship",
    "loco-rs/loco",
    "extism/extism",
    "rust-lang/rust",
    "rust-lang/cargo",
    "rust-lang/rustup",
    "serde-rs/serde",
    "tokio-rs/axum",
    "actix/actix-web",
    "rocket-rs/rocket",
    "hyperium/hyper",
    "hyperium/tonic",
    "rayon-rs/rayon",
    "crossbeam-rs/crossbeam",
    "BurntSushi/ripgrep",
    "sharkdp/fd",
    "sharkdp/bat",
    "ajeetdsouza/zoxide",
    "nushell/nushell",
    "wezterm/wezterm",
    "alacritty/alacritty",
    "emilk/egui",
    "slint-ui/slint",
    "tauri-apps/wry",
    "dtolnay/anyhow",
    "dtolnay/thiserror",
    "clap-rs/clap",
    "rust-lang/mdBook",
  ],
};

/**
 * Flattened list of every seed repo. Iteration order follows the category
 * order declared above — useful when chunking through a cold-boot seed so
 * early batches cover a variety of categories.
 */
export const ALL_SEED_REPOS: string[] = Object.values(SEED_REPOS).flat();
