// StarScreener Pipeline — Classification Rules
//
// Rule-based first-pass category classifier. Each rule defines topic,
// keyword, and owner-prefix signals that imply a given PipelineCategoryId.
// The classifier engine consumes these rules and ranks by weighted score.
//
// Weights are baseline multipliers (1.0-2.0). Higher weight = more
// authoritative rule. MCP has the highest weight (2.0) because it is a
// narrow, unambiguous category — any MCP signal is a strong assertion.

import type { ClassificationRule } from "../types";

export const CLASSIFICATION_RULES: ClassificationRule[] = [
  {
    categoryId: "ai-agents",
    topics: [
      "ai-agent",
      "llm-agent",
      "autonomous-agent",
      "agent",
      "agents",
      "multi-agent",
    ],
    keywords: [
      "ai agent",
      "llm agent",
      "autonomous agent",
      "multi-agent",
      "agentic",
    ],
    ownerPrefixes: [
      "langchain-ai",
      "crewAIInc",
      "microsoft/autogen",
      "stanfordnlp",
    ],
    weight: 1.5,
  },
  {
    categoryId: "mcp",
    topics: ["mcp", "model-context-protocol"],
    keywords: ["model context protocol", "mcp server", "mcp client"],
    ownerPrefixes: ["modelcontextprotocol", "anthropics"],
    weight: 2.0,
  },
  {
    categoryId: "devtools",
    topics: [
      "cli",
      "linter",
      "formatter",
      "bundler",
      "build-tool",
      "developer-tools",
      "dx",
      "build-system",
    ],
    keywords: [
      "cli tool",
      "build tool",
      "linter",
      "formatter",
      "bundler",
      "package manager",
    ],
    ownerPrefixes: [
      "astral-sh",
      "oven-sh",
      "biomejs",
      "oxc-project",
      "swc-project",
    ],
    weight: 1.2,
  },
  {
    categoryId: "browser-automation",
    topics: [
      "browser-automation",
      "playwright",
      "puppeteer",
      "selenium",
      "scraping",
      "web-automation",
    ],
    keywords: [
      "browser automation",
      "headless browser",
      "web scraping",
      "e2e testing",
    ],
    ownerPrefixes: ["microsoft/playwright", "puppeteer", "browserless"],
    weight: 1.6,
  },
  {
    categoryId: "local-llm",
    topics: [
      "local-llm",
      "ollama",
      "llama",
      "local-ai",
      "llama-cpp",
      "gguf",
    ],
    keywords: [
      "local llm",
      "local inference",
      "llama.cpp",
      "ollama",
      "run locally",
    ],
    ownerPrefixes: ["ollama", "ggerganov", "mlc-ai", "open-webui"],
    weight: 1.6,
  },
  {
    categoryId: "security",
    topics: [
      "security",
      "vulnerability",
      "cve",
      "scanner",
      "secret-scanning",
      "sast",
      "pentest",
      "appsec",
    ],
    keywords: [
      "security scanner",
      "vulnerability",
      "secret scanner",
      "pentesting",
      "sast",
    ],
    ownerPrefixes: [
      "projectdiscovery",
      "trufflesecurity",
      "aquasecurity",
      "gitleaks",
      "semgrep",
      "snyk",
      "zaproxy",
      "crowdsecurity",
    ],
    weight: 1.3,
  },
  {
    categoryId: "infrastructure",
    topics: [
      "infrastructure",
      "kubernetes",
      "terraform",
      "docker",
      "devops",
      "cloud",
      "iac",
      "orchestration",
    ],
    keywords: [
      "infrastructure as code",
      "kubernetes",
      "cloud platform",
      "container orchestration",
    ],
    ownerPrefixes: [
      "kubernetes",
      "hashicorp",
      "docker",
      "pulumi",
      "grafana",
      "traefik",
      "cloudflare",
    ],
    weight: 1.2,
  },
  {
    categoryId: "design-engineering",
    topics: [
      "design-system",
      "component-library",
      "ui-library",
      "figma",
      "design-tokens",
      "ui-kit",
    ],
    keywords: [
      "design system",
      "component library",
      "ui kit",
      "design tokens",
    ],
    ownerPrefixes: ["shadcn-ui", "radix-ui", "mantinedev"],
    weight: 1.4,
  },
  {
    categoryId: "ai-ml",
    topics: [
      "machine-learning",
      "deep-learning",
      "transformers",
      "pytorch",
      "tensorflow",
      "llm",
      "ai",
      "neural-network",
    ],
    keywords: [
      "machine learning",
      "deep learning",
      "neural network",
      "transformer model",
      "language model",
    ],
    ownerPrefixes: [
      "huggingface",
      "openai",
      "pytorch",
      "tensorflow",
      "run-llama",
      "mistralai",
    ],
    weight: 1.0,
  },
  {
    categoryId: "web-frameworks",
    topics: [
      "web-framework",
      "ssr",
      "jamstack",
      "react-framework",
      "react",
      "vue",
      "svelte",
      "astro",
      "solidjs",
    ],
    keywords: ["web framework", "full-stack framework", "react framework"],
    ownerPrefixes: [
      "vercel",
      "sveltejs",
      "vuejs",
      "remix-run",
      "withastro",
      "honojs",
      "solidjs",
      "angular",
      "nuxt",
    ],
    weight: 1.3,
  },
  {
    categoryId: "databases",
    topics: [
      "database",
      "sql",
      "nosql",
      "vector-database",
      "time-series",
      "graph-database",
      "key-value",
    ],
    keywords: [
      "database",
      "sql engine",
      "vector db",
      "time-series",
      "key-value store",
    ],
    ownerPrefixes: [
      "duckdb",
      "pola-rs",
      "cockroachdb",
      "timescale",
      "surrealdb",
      "turso-tech",
      "dragonflydb",
      "valkey-io",
    ],
    weight: 1.3,
  },
  {
    categoryId: "mobile",
    topics: [
      "ios",
      "android",
      "mobile",
      "react-native",
      "flutter",
      "expo",
      "swiftui",
      "kotlin",
    ],
    keywords: ["mobile app", "ios", "android", "react native", "flutter"],
    ownerPrefixes: ["expo", "tauri-apps", "nicklockwood", "altstore"],
    weight: 1.3,
  },
  {
    categoryId: "data-analytics",
    topics: [
      "analytics",
      "bi",
      "data-visualization",
      "dashboard",
      "etl",
      "data-pipeline",
      "olap",
    ],
    keywords: [
      "analytics platform",
      "business intelligence",
      "data visualization",
      "etl",
      "data pipeline",
    ],
    ownerPrefixes: [
      "apache/superset",
      "metabase",
      "evidence-dev",
      "streamlit",
      "grafana/loki",
    ],
    weight: 1.2,
  },
  {
    categoryId: "crypto-web3",
    topics: [
      "blockchain",
      "ethereum",
      "solana",
      "web3",
      "defi",
      "smart-contracts",
      "crypto",
    ],
    keywords: ["blockchain", "ethereum client", "smart contract", "defi"],
    ownerPrefixes: [
      "paradigmxyz",
      "foundry-rs",
      "solana-labs",
      "ethereum",
      "alloy-rs",
      "a16z",
      "starkware-libs",
      "MystenLabs",
    ],
    weight: 1.3,
  },
  {
    categoryId: "rust-ecosystem",
    topics: ["rust", "rust-lang", "cargo", "rust-crate"],
    keywords: [],
    ownerPrefixes: [
      "tokio-rs",
      "leptos-rs",
      "bevyengine",
      "meilisearch",
      "starship",
      "loco-rs",
      "extism",
    ],
    weight: 1.1,
  },
];
