import { describe, expect, it } from 'vitest';

import pairsData from '../pairs.json' with { type: 'json' };
import { compareKey } from '../prompt.js';

interface ComparePairSeed {
  a: string;
  b: string;
}
const PAIRS = pairsData as ComparePairSeed[];

// Structural sentinel for the committed compare-pairs snapshot. The set itself
// is data-derived (regenerated by scripts/dump-compare-pairs.ts from the app's
// selectComparablePairs), so a strict equality test can't run in CI without the
// data-store — instead we validate the artifact's shape + invariants the worker
// relies on. Regenerate the snapshot when the curated set drifts.
describe('editorial-compare pairs.json', () => {
  it('is a non-empty array of pairs', () => {
    expect(Array.isArray(PAIRS)).toBe(true);
    expect(PAIRS.length).toBeGreaterThan(0);
  });

  it('every entry is two distinct owner/name fullNames', () => {
    for (const p of PAIRS) {
      expect(typeof p.a).toBe('string');
      expect(typeof p.b).toBe('string');
      expect(p.a).toMatch(/^[^/]+\/[^/]+$/);
      expect(p.b).toMatch(/^[^/]+\/[^/]+$/);
      expect(p.a.toLowerCase()).not.toBe(p.b.toLowerCase());
    }
  });

  it('pairs are alphabetically ordered (a < b) — canonical key order', () => {
    for (const p of PAIRS) {
      expect(p.a.toLowerCase() <= p.b.toLowerCase()).toBe(true);
      // compareKey must round-trip to the same ordering.
      expect(compareKey(p.a, p.b)).toBe(`${p.a}__vs__${p.b}`);
    }
  });

  it('has no duplicate pairs', () => {
    const keys = PAIRS.map((p) => compareKey(p.a, p.b));
    expect(new Set(keys).size).toBe(keys.length);
  });
});
