// TrendingRepo — /feeds/[slug].xml
//
// Per-category RSS 2.0 feed. One feed per category id (see CATEGORIES in
// src/lib/constants.ts) — 32 axes today, kept dynamic so adding a category
// adds a feed automatically.
//
// Why this exists: the 2026-06-14 competitive review (PR #3171) found that
// no competing GitHub-trending surface (OSSInsight, TrendShift, etc.) ships
// RSS/webhook surfaces. Per-category feeds extend the moat to crawlers,
// feed readers, and AI agents that consume via /llms.txt → RSS.
//
// Companion to the 32-axis NanoGPT classifier (PR #3185). Until that
// classifier populates a richer per-repo categorization map, the feed
// filters by the existing `categoryId` field on derived-repos.
//
// Freshness: gated by the consensus-trending payload's `computedAt`. RSS
// readers tolerate slightly longer staleness than UI surfaces (most poll
// every 5–60 min), so we accept up to 4h of staleness before emitting a
// single "refreshing" placeholder <item> instead of stale rows.

import type { NextRequest } from "next/server";
import { CATEGORIES } from "@/lib/constants";
import { getDerivedRepos } from "@/lib/derived-repos";
import {
  getConsensusTrendingMeta,
  refreshConsensusTrendingFromStore,
} from "@/lib/consensus-trending";
import {
  getConsensusItemReport,
  refreshConsensusVerdictsFromStore,
} from "@/lib/consensus-verdicts";
import { renderRssFeed, type RssItem } from "@/lib/feeds/rss";
import { absoluteUrl, SITE_NAME } from "@/lib/seo";
import type { Repo } from "@/lib/types";

export const runtime = "nodejs";
export const dynamic = "force-dynamic";
export const revalidate = 900; // 15 minutes — matches Cache-Control

const MAX_ITEMS = 25;
const STALE_THRESHOLD_MS = 4 * 60 * 60 * 1000; // 4h

function parseCategorySlug(pathname: string): string | null {
  const match = pathname.match(/^\/feeds\/([^/]+)\.xml$/);
  return match?.[1] ?? null;
}

function pickPubDate(lastCommitAt: string, lastReleaseAt: string | null): string {
  const commit = Date.parse(lastCommitAt);
  const release = lastReleaseAt ? Date.parse(lastReleaseAt) : NaN;
  const candidates: number[] = [];
  if (Number.isFinite(commit)) candidates.push(commit);
  if (Number.isFinite(release)) candidates.push(release);
  if (candidates.length === 0) return new Date().toISOString();
  return new Date(Math.max(...candidates)).toISOString();
}

function buildItemDescription(repo: Repo): string {
  // Prefer the ConsensusItemReport.summary when the verdicts payload covers
  // this repo (it's a richer one-liner generated by the NanoGPT verdict pass).
  // Fall back to the repo's own description otherwise.
  const report = getConsensusItemReport(repo.fullName);
  const summary =
    report && report.summary.trim().length > 0
      ? report.summary
      : repo.description?.trim() ?? "";

  const lines: string[] = [];
  if (summary) lines.push(`<p>${summary}</p>`);
  const meta: string[] = [];
  meta.push(`${repo.stars.toLocaleString("en-US")} stars`);
  if (repo.momentumScore > 0) {
    meta.push(`momentum ${repo.momentumScore.toFixed(1)}`);
  }
  if (repo.language) meta.push(repo.language);
  lines.push(`<p><em>${meta.join(" · ")}</em></p>`);
  return lines.join("\n");
}

function buildIndexingPlaceholder(
  categoryName: string,
  feedLink: string,
): RssItem {
  return {
    title: `${categoryName} — indexing in progress`,
    link: feedLink,
    guid: `${feedLink}#indexing`,
    pubDate: new Date().toISOString(),
    description:
      "<p>Trending data is warming for this category. The feed will populate as soon as the classifier and consensus pool catch up.</p>",
  };
}

function buildStalePlaceholder(
  categoryName: string,
  feedLink: string,
  computedAt: string,
): RssItem {
  const since =
    computedAt && Number.isFinite(Date.parse(computedAt))
      ? new Date(computedAt).toUTCString()
      : "unknown";
  return {
    title: `${categoryName} — feed stale, trending data refreshing`,
    link: feedLink,
    guid: `${feedLink}#stale`,
    pubDate: new Date().toISOString(),
    description: `<p>Upstream trending data hasn't refreshed since ${since}. Returning a placeholder rather than serving stale rankings — check back in a few minutes.</p>`,
  };
}

export async function GET(req: NextRequest): Promise<Response> {
  const slug = parseCategorySlug(req.nextUrl.pathname);
  const category = CATEGORIES.find((c) => c.id === slug);

  if (!category) {
    return new Response("Not Found", {
      status: 404,
      headers: { "Content-Type": "text/plain; charset=utf-8" },
    });
  }

  // Refresh in parallel; both readers no-op within 30s windows so this is
  // cheap on warm Lambdas.
  await Promise.all([
    refreshConsensusTrendingFromStore(),
    refreshConsensusVerdictsFromStore(),
  ]);

  const meta = getConsensusTrendingMeta();
  const feedLink = absoluteUrl(`/feeds/${slug}.xml`);
  const categoryUrl = absoluteUrl(`/categories/${slug}`);

  const channelTitle = `${SITE_NAME} — ${category.name}`;
  const channelDescription = category.description;

  const repos = getDerivedRepos().filter((r) => r.categoryId === slug);

  // Honor the no-publicly-stale-batches rule: when the consensus payload is
  // older than 4h (or missing entirely), surface a placeholder <item> rather
  // than emit stale rows.
  const ageMs = meta.ageSeconds * 1000;
  const computedTs = meta.computedAt ? Date.parse(meta.computedAt) : NaN;
  const computedAge = Number.isFinite(computedTs)
    ? Date.now() - computedTs
    : ageMs;
  const isStale =
    meta.source === "missing" ||
    !meta.computedAt ||
    computedAge > STALE_THRESHOLD_MS;

  let items: RssItem[];
  let lastBuildDate: string;

  if (isStale && repos.length > 0) {
    items = [buildStalePlaceholder(category.name, feedLink, meta.computedAt)];
    lastBuildDate = new Date().toISOString();
  } else if (repos.length === 0) {
    // Pool hasn't classified anything into this category yet — surface an
    // explicit placeholder so feed readers see a valid <item> instead of an
    // empty channel.
    items = [buildIndexingPlaceholder(category.name, feedLink)];
    lastBuildDate = new Date().toISOString();
  } else {
    // Sort by momentum (sector signal) and pick the 25 most active. PubDate
    // is the per-repo `max(lastCommitAt, lastReleaseAt)` — the recency
    // signal aggregators key off when they de-dup items across polls.
    const sorted = [...repos].sort((a, b) => {
      if (b.momentumScore !== a.momentumScore) {
        return b.momentumScore - a.momentumScore;
      }
      return b.stars - a.stars;
    });

    items = sorted.slice(0, MAX_ITEMS).map((repo) => {
      const link = absoluteUrl(`/repo/${repo.owner}/${repo.name}`);
      return {
        title: repo.fullName,
        link,
        guid: link,
        pubDate: pickPubDate(repo.lastCommitAt, repo.lastReleaseAt),
        description: buildItemDescription(repo),
        author: repo.owner,
        categories: [category.id, repo.language ?? ""].filter(Boolean),
      };
    });

    lastBuildDate = meta.computedAt || new Date().toISOString();
  }

  const xml = renderRssFeed({
    title: channelTitle,
    link: categoryUrl, // channel <link> points at the human page
    description: channelDescription,
    lastBuildDate,
    items,
  });

  return new Response(xml, {
    status: 200,
    headers: {
      "Content-Type": "application/rss+xml; charset=utf-8",
      "Cache-Control": "public, s-maxage=900, stale-while-revalidate=3600",
    },
  });
}
