#!/usr/bin/env node
// scripts/derive-openapi.mjs
//
// Walks src/app/api/**/route.ts, derives the OpenAPI URL path from the
// directory layout (Next.js App Router => [param] becomes {param}), and
// regex-extracts the exported HTTP methods (GET/POST/PATCH/DELETE/PUT) plus
// any local zod schemas it can spot. Emits a stub spec at
// docs/_generated/openapi-derived.yaml.
//
// Pure Node 22 ESM, no new deps. Schemas are NOT translated to JSON Schema
// here — that would need @asteasolutions/zod-to-openapi (not installed).
// Instead, each operation gets a `# TODO: schema not yet wired` line so a
// human review pass can wire schemas surgically without us guessing the
// shape. This script is intentionally read-only: it never touches
// docs/openapi.yaml.

import {
  readdirSync,
  readFileSync,
  mkdirSync,
  writeFileSync,
} from "node:fs";
import { join, relative, sep } from "node:path";
import { fileURLToPath } from "node:url";

const ROOT = join(fileURLToPath(import.meta.url), "..", "..");
const API_ROOT = join(ROOT, "src", "app", "api");
const OUT_DIR = join(ROOT, "docs", "_generated");
const OUT_FILE = join(OUT_DIR, "openapi-derived.yaml");

const HTTP_METHODS = ["GET", "POST", "PATCH", "DELETE", "PUT"];

function walk(dir, acc = []) {
  let entries;
  try {
    entries = readdirSync(dir, { withFileTypes: true });
  } catch {
    return acc;
  }
  for (const entry of entries) {
    const full = join(dir, entry.name);
    if (entry.isDirectory()) walk(full, acc);
    else if (entry.isFile() && entry.name === "route.ts") acc.push(full);
  }
  return acc;
}

// Convert a route.ts file path to its public URL path.
//   src/app/api/repos/[owner]/[name]/route.ts
//     -> /api/repos/{owner}/{name}
// Decodes URL-percent escapes already present on disk (e.g. %5Finternal -> _internal).
function fileToRoute(filePath) {
  const rel = relative(join(ROOT, "src", "app"), filePath).split(sep);
  // Drop trailing "route.ts"
  rel.pop();
  const parts = rel.map((seg) => {
    let decoded = seg;
    try {
      decoded = decodeURIComponent(seg);
    } catch {
      // leave as-is
    }
    if (decoded.startsWith("[") && decoded.endsWith("]")) {
      const inner = decoded.slice(1, -1);
      // Catch-all routes: [...slug] -> {slug} (best-effort)
      if (inner.startsWith("...")) return `{${inner.slice(3)}}`;
      return `{${inner}}`;
    }
    return decoded;
  });
  return "/" + parts.join("/");
}

// Regex-detect HTTP method exports. Matches:
//   export async function GET(...)
//   export function POST(...)
//   export const GET = ...
function detectMethods(source) {
  const methods = new Set();
  for (const m of HTTP_METHODS) {
    const re = new RegExp(
      `export\\s+(?:async\\s+)?(?:function|const|let)\\s+${m}\\b`,
    );
    if (re.test(source)) methods.add(m);
  }
  return Array.from(methods);
}

// Best-effort zod schema discovery. Looks for top-level
//   const FooSchema = z.object(...)
//   const FooSchema = z.union(...)
//   const FooSchema = z.discriminatedUnion(...)
// and returns the names. We don't try to compile/translate.
function detectZodSchemas(source) {
  const names = [];
  const re = /const\s+([A-Z][A-Za-z0-9_]*Schema)\s*=\s*z\.(object|union|discriminatedUnion|array|record|tuple)\b/g;
  let m;
  while ((m = re.exec(source)) !== null) {
    names.push(m[1]);
  }
  return names;
}

// Naive YAML string emitter — quotes keys/values that need it. We control
// every value here (paths, method names, schema names) so this is safe
// without a full YAML lib.
function yamlEscape(value) {
  if (typeof value !== "string") return String(value);
  // Quote when value contains chars that confuse YAML's plain scalar scanner.
  if (/[:#{}\[\],&*!|>'"%@`]|^\s|\s$/.test(value)) {
    return `"${value.replace(/"/g, '\\"')}"`;
  }
  return value;
}

function emit(routes) {
  const lines = [];
  const lastVerified = new Date().toISOString().slice(0, 10);
  lines.push("# status: snapshot");
  lines.push(`# last-verified: ${lastVerified}`);
  lines.push("# verified-by: scripts/derive-openapi.mjs");
  lines.push("# reason: auto-generated OpenAPI stub; manual review needed before merging into docs/openapi.yaml");
  lines.push("# AUTO-GENERATED by scripts/derive-openapi.mjs — DO NOT EDIT BY HAND.");
  lines.push("# This is a stub spec derived from src/app/api/**/route.ts.");
  lines.push("# Compare against docs/openapi.yaml via scripts/check-openapi-coverage.mjs.");
  lines.push(`# Generated at: ${new Date().toISOString()}`);
  lines.push("openapi: 3.1.0");
  lines.push("info:");
  lines.push("  title: TrendingRepo API (derived)");
  lines.push("  version: 0.0.0-derived");
  lines.push("  description: |");
  lines.push("    Auto-derived stub from filesystem walk. Each operation is a");
  lines.push("    placeholder; schemas need to be wired in docs/openapi.yaml manually.");
  lines.push("paths:");

  const sorted = [...routes].sort((a, b) => a.route.localeCompare(b.route));
  for (const r of sorted) {
    lines.push(`  ${yamlEscape(r.route)}:`);
    if (r.methods.length === 0) {
      lines.push("    # TODO: no HTTP method export detected; verify the route file");
      continue;
    }
    for (const method of r.methods) {
      lines.push(`    ${method.toLowerCase()}:`);
      lines.push(`      operationId: ${operationId(r.route, method)}`);
      lines.push(`      summary: ${yamlEscape(`Auto-derived stub for ${method} ${r.route}`)}`);
      // Source pointer for review
      lines.push(`      x-source-file: ${yamlEscape(r.relFile)}`);
      if (r.schemas.length > 0) {
        lines.push("      x-detected-zod-schemas:");
        for (const name of r.schemas) {
          lines.push(`        - ${yamlEscape(name)}`);
        }
        lines.push("      # TODO: schemas detected but not yet wired (needs zod-to-openapi)");
      } else {
        lines.push("      # TODO: schema not yet wired");
      }
      lines.push("      responses:");
      lines.push("        '200':");
      lines.push("          description: Success (shape unknown — see x-source-file)");
    }
  }
  return lines.join("\n") + "\n";
}

function operationId(route, method) {
  // /api/repos/{owner}/{name}/aiso  +  GET  =>  getApiReposByOwnerByNameAiso
  const segs = route.split("/").filter(Boolean);
  const camel = segs
    .map((s) => {
      if (s.startsWith("{") && s.endsWith("}")) {
        const name = s.slice(1, -1);
        return "By" + name.charAt(0).toUpperCase() + name.slice(1);
      }
      return s
        .split(/[-_.]/)
        .filter(Boolean)
        .map((p, i) => (i === 0 ? p : p.charAt(0).toUpperCase() + p.slice(1)))
        .join("")
        .replace(/^(.)/, (c) => c.toUpperCase());
    })
    .join("");
  return method.toLowerCase() + camel;
}

function main() {
  const files = walk(API_ROOT);
  const routes = [];
  for (const file of files) {
    let source = "";
    try {
      source = readFileSync(file, "utf8");
    } catch (err) {
      process.stderr.write(`[derive-openapi] read failed: ${file}: ${err && err.message}\n`);
      continue;
    }
    const route = fileToRoute(file);
    const methods = detectMethods(source);
    const schemas = detectZodSchemas(source);
    routes.push({
      route,
      methods,
      schemas,
      relFile: relative(ROOT, file).split(sep).join("/"),
    });
  }

  const yaml = emit(routes);
  mkdirSync(OUT_DIR, { recursive: true });
  writeFileSync(OUT_FILE, yaml, "utf8");

  // Summary to stdout for the verify step.
  const totalOps = routes.reduce((acc, r) => acc + r.methods.length, 0);
  const withSchemas = routes.filter((r) => r.schemas.length > 0).length;
  process.stdout.write(
    `[derive-openapi] routes=${routes.length} operations=${totalOps} routes_with_zod=${withSchemas}\n`,
  );
  process.stdout.write(`[derive-openapi] wrote ${relative(ROOT, OUT_FILE).split(sep).join("/")}\n`);
}

main();
