// RepoSignalSummary — Profile-standalone "Signal Summary" prose card.
//
// 1:1 port of the PFSummary tree in the standalone Profile HTML reference
// (asset_e0686a47.js lines 488-533), wired to live data: every paragraph
// is generated by `synthesizeWhyParagraphs` (see src/lib/why-narrative.ts)
// from the page's already-fetched repo / community / profile spine. No
// network calls; no client-side state; pure server component.
//
// Prose-driver contract: every sentence is owned by the why-narrative
// generator. The component only parses three lightweight markup tokens
// the generator emits — [num]…[/num], [em]…[/em], [strong]…[/strong] —
// and turns them into the CSS classes the standalone uses (.num, plain
// <em>, <strong>). NO hand-written paragraph text lives in this file.
//
// Card head — left: `// WHY IT'S TRENDING · narrative synthesis · medium
// confidence`. Right: AISO credit pill linking to aiso.tools (the brand
// glyph is the "A" .mark span — gradient circle, no inline hex).
//
// Card foot — left: status bag (refreshed Nm ago · next sync in Nm ·
// sourced from N channels · N mentions / 24h). Right: a link out to the
// per-repo AISO deep brief.

import { ageLabel } from "@/lib/format-age";
import { synthesizeWhyParagraphs, type WhyConfidence } from "@/lib/why-narrative";
import { SourceLogo } from "@/components/icon/Icon";

import type { ConsensusItemReport } from "@/lib/consensus-verdicts";
import type { RepoCommunityProfile } from "@/lib/repo-community-profile";
import type { RepoProfile } from "@/lib/repo-profiles";
import type { Repo } from "@/lib/types";

interface RepoSignalSummaryProps {
  repo: Repo;
  community: RepoCommunityProfile | null;
  profile: RepoProfile | null;
  /**
   * AISO/Kimi consensus verdict for this repo, when one exists in the
   * `consensus-verdicts` store. When present (and non-empty) it is the
   * source of truth for the prose and the page shows real AISO attribution.
   * When null, we fall back to the local deterministic `synthesizeWhyParagraphs`
   * and drop the AISO badge — no fake attribution on template prose.
   */
  consensusItem?: ConsensusItemReport | null;
  /** ISO timestamp from the page (passed through from `getLastFetchedAt()`). */
  fetchedAt?: string | null;
}

// Authority framing — never dismissive. The displayed category is derived
// from the real scores, so an established high-adoption project reads
// "ESTABLISHED LEADER" rather than a low-signal label, and a genuine
// multi-source breakout reads "MULTI-SOURCE CONSENSUS". Never "WEAK"/"NOISE".
function displaySignalLabel(item: ConsensusItemReport): string {
  const cross = item.scores.crossSource;
  const adoption = item.scores.developerAdoption;
  if (cross >= 70) return "MULTI-SOURCE CONSENSUS";
  if (cross >= 36 || item.verdict === "early") {
    return adoption >= 78 ? "ESTABLISHED · GAINING" : "EARLY MOMENTUM";
  }
  if (adoption >= 72) return "ESTABLISHED LEADER";
  return "EMERGING SIGNAL";
}

const ACTION_LABEL: Record<ConsensusItemReport["whatToDo"], string> = {
  watch: "Watch",
  build: "Build on it",
  ignore: "Ignore",
  research: "Research",
};

// Trending cron runs every hour at minute 27 (see docs/ENGINE.md). The
// next-sync clock counts down to the next :27 from "now". When we can't
// derive a sane number (clock skew, etc.) we degrade to "soon" rather
// than print a bogus minute count.
const TRENDING_CRON_MINUTE = 27;

function minutesUntilNextSync(nowMs: number = Date.now()): number | null {
  const now = new Date(nowMs);
  const currentMin = now.getMinutes();
  const diff = (TRENDING_CRON_MINUTE - currentMin + 60) % 60;
  // If we're exactly on the cron minute, treat as "0m" rather than 60.
  if (!Number.isFinite(diff) || diff < 0 || diff > 60) return null;
  return diff;
}

// Parse the [num]/[em]/[strong] marker tokens emitted by the prose
// generator into a JSX fragment array. Tokens never nest (the generator
// guarantees this), so a single linear scan is enough.
const TOKEN_RE = /\[(num|em|strong)\]([\s\S]*?)\[\/\1\]/g;

function renderParagraph(text: string, key: number): React.ReactNode {
  const nodes: React.ReactNode[] = [];
  let cursor = 0;
  let nodeKey = 0;
  TOKEN_RE.lastIndex = 0;
  let match: RegExpExecArray | null;
  while ((match = TOKEN_RE.exec(text)) !== null) {
    if (match.index > cursor) {
      nodes.push(text.slice(cursor, match.index));
    }
    const [, tag, inner] = match;
    if (tag === "num") {
      nodes.push(
        <span key={`n-${nodeKey++}`} className="num">
          {inner}
        </span>,
      );
    } else if (tag === "em") {
      nodes.push(<em key={`e-${nodeKey++}`}>{inner}</em>);
    } else {
      nodes.push(<strong key={`s-${nodeKey++}`}>{inner}</strong>);
    }
    cursor = match.index + match[0].length;
  }
  if (cursor < text.length) {
    nodes.push(text.slice(cursor));
  }
  return <p key={`p-${key}`}>{nodes}</p>;
}

function confidenceLabel(c: WhyConfidence): string {
  return `${c} confidence`;
}

export function RepoSignalSummary({
  repo,
  community,
  profile,
  consensusItem,
  fetchedAt,
}: RepoSignalSummaryProps) {
  // Source of truth: a real AISO/Kimi verdict when present and non-empty;
  // otherwise the local deterministic synthesis. This single boolean drives
  // both the prose AND the attribution honesty (no AISO badge on fallback).
  const hasVerdict = Boolean(consensusItem && consensusItem.summary.trim().length > 0);

  const { paragraphs, confidence } = synthesizeWhyParagraphs(repo, community, profile);

  // Refreshed-ago: prefer the page-level fetchedAt (data spine), fall back
  // to the community-profile timestamp when the spine wasn't passed in.
  const refreshedIso = fetchedAt ?? community?.fetchedAt ?? null;
  const refreshedAgo = ageLabel(refreshedIso);

  const nextSyncMin = minutesUntilNextSync();
  const nextSyncLabel =
    nextSyncMin === null ? "soon" : nextSyncMin === 0 ? "now" : `${nextSyncMin}m`;

  const channelsFiring = typeof repo.channelsFiring === "number" ? repo.channelsFiring : 0;
  const mentions24h = repo.mentions?.total24h ?? repo.mentionCount24h ?? 0;
  const briefHref = `https://aiso.tools/r/${repo.fullName}`;

  // Subtitle: real verdict → "expert verdict · {confidence}% confidence";
  // fallback → "narrative synthesis · {level} confidence".
  const subtitle = hasVerdict
    ? `· expert verdict · ${consensusItem!.confidence}% confidence`
    : `· narrative synthesis · ${confidenceLabel(confidence)}`;

  const body = hasVerdict ? (
    <ConsensusBody item={consensusItem!} />
  ) : paragraphs.length > 0 ? (
    paragraphs.map((p, i) => renderParagraph(p, i))
  ) : (
    <p>
      Narrative synthesis coming soon — meanwhile, see the constellation and stats below.
    </p>
  );

  return (
    <section className="pf-section">
      <div className="pf-summary">
        <div className="pf-summary-head">
          <div className="l">
            <span className="slash">{"//"}</span>
            <span>WHY IT&apos;S TRENDING</span>
            <span className="dim">{subtitle}</span>
          </div>
          {hasVerdict ? (
            <div className="r">
              <a
                className="aiso-credit"
                href={briefHref}
                target="_blank"
                rel="noopener noreferrer"
              >
                <SourceLogo
                  source="aiso"
                  size={16}
                  alt=""
                  className="mark"
                  style={{ borderRadius: 3, flexShrink: 0 }}
                />
                <span>ANALYSIS BY AISO.TOOLS</span>
                <span className="arr" aria-hidden>
                  ↗
                </span>
              </a>
            </div>
          ) : null}
        </div>
        <div className="pf-summary-body">{body}</div>
        <div className="pf-summary-foot">
          <div className="bag">
            <span>↻ refreshed {refreshedAgo}</span>
            <span>· next sync in {nextSyncLabel}</span>
            <span>
              · sourced from {channelsFiring} channel{channelsFiring === 1 ? "" : "s"} · {mentions24h} mention{mentions24h === 1 ? "" : "s"} / 24h
            </span>
          </div>
          {hasVerdict ? (
            <div>
              <a href={briefHref} target="_blank" rel="noopener noreferrer">
                see full AISO brief ↗
              </a>
            </div>
          ) : null}
        </div>
        {hasVerdict ? (
          <p className="pf-summary-method">
            Methodology: synthesized from this project&apos;s own documentation,
            live GitHub data, third-party coverage, and multi-platform signal
            convergence — by{" "}
            <a href="https://aiso.tools" target="_blank" rel="noopener noreferrer">
              AISO.tools
            </a>
            .
          </p>
        ) : null}
      </div>
    </section>
  );
}

/**
 * Renders a real AISO/Kimi consensus verdict: summary + whyNow as prose,
 * evidence as a bullet list, a contrarian counter-line, and an action
 * callout. All fields are plain text (no marker tokens), so no token parser.
 */
function ConsensusBody({ item }: { item: ConsensusItemReport }) {
  return (
    <>
      {item.tagline && item.tagline.trim().length > 0 ? (
        <p className="pf-summary-tagline">
          <strong>{item.tagline}</strong>
        </p>
      ) : null}
      <p>{item.summary}</p>
      {item.whyNow.trim().length > 0 ? (
        <p>
          <strong>Why now: </strong>
          {item.whyNow}
        </p>
      ) : null}
      {item.evidence.length > 0 ? (
        <ul className="pf-summary-evidence">
          {item.evidence.map((point, i) => (
            <li key={i}>{point}</li>
          ))}
        </ul>
      ) : null}
      {item.contrarian.trim().length > 0 ? (
        <p className="pf-summary-contrarian">
          <strong>Considerations: </strong>
          <em>{item.contrarian}</em>
        </p>
      ) : null}
      <p className="pf-summary-action">
        <span className="num">{displaySignalLabel(item)}</span>
        {" · "}
        <strong>{ACTION_LABEL[item.whatToDo]}: </strong>
        {item.whatToDoDetail}
      </p>
      {item.citations && item.citations.length > 0 ? (
        <p className="pf-summary-sources">
          <strong>Sources: </strong>
          {item.citations.map((c, i) => (
            <span key={c.url}>
              {i > 0 ? " · " : ""}
              <a href={c.url} target="_blank" rel="noopener noreferrer">
                {c.title}
              </a>
            </span>
          ))}
        </p>
      ) : null}
    </>
  );
}
